### PR TITLE
Add Record ID to EmailTag List

### PR DESCRIPTION
**Pull request by KirschnerMatt**

### CODE REVIEW

**Comment by PerplexDaniel** [comment]
Hey Matthew,

Thanks for the pull request, Jeffrey notified me about it. I just commited a change which adds some more fields, including the record id like you suggested here. However, we include the GUID (record.UniqueId) rather than the int, as record.Id was not initialized yet when the Workflow was executed, presumably as the record at that point is not yet committed to the database (can still be rejected). You can see all changes in the commit log. I'm closing this now as the latest commit supersedes it!

**Comment by KirschnerMatt** [comment]
Hi, Daniel.

Please put the record id (int) back in. The integer id is initialized if you enable post moderation on your form in settings. I think this is dumb, but that's the way Forms currently works.

I enable post moderation on all my forms now as we really need that record id to be sent to the user as a confirmation number. The GUID is kinda worthless in this regard.

**Comment by PerplexDaniel** [comment]
Hi Matthew,

I have pushed a new change which now includes both [#recordId#] and [#recordUniqueId#] to point to both properties of record.

**Comment by KirschnerMatt** [comment]
Fantastic, thanks!

**Pull request closed without merging**
